POST http://localhost:8080/api/spread
Content-Type: application/json
X-ROOM-ID: test1
X-USER-ID: testUser1

{
  "money": 13000,
  "memberNum": 2
}

###

POST http://localhost:8080/api/receive
Content-Type: application/json
X-ROOM-ID: test1
X-USER-ID: testUser2

{
  "apiToken": "COr"
}

###


POST http://localhost:8080/api/list
Content-Type: application/json
X-ROOM-ID: test1
X-USER-ID: testUser1

{
  "apiToken": "COr"
}

###

